# Generated by Django 5.2.6 on 2025-09-23 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='SecretChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='secretchild.employee')),
                ('secret_child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='secretchild.employee')),
            ],
            options={
                'verbose_name': 'secretchild',
                'verbose_name_plural': 'secretchildren',
                'db_table': 'secretchild',
            },
        ),
    ]
